### ISSUE TITLE
Overlapping tex code space overlaps generate button

### ISSUE THREAD

**Issue by ghost** [aratno/lipqn#1]
Some large rendered elements leaves the rendered class overlapping the 'h1' title element, making it un-clickable in the affected area. Should be a simple positioning fix.

![screen shot 2015-11-08 at 9 38 35 pm](https://cloud.githubusercontent.com/assets/8469231/11024771/6425253c-8661-11e5-9ce2-b9975d621805.png)

**Comment by aratno** [comment]
I'm aware this happens sometimes and I'm only okay with it because I'm working on a full redesign.
